openapi: 3.1.0
info:
  version: 1.0.0
  title: 7WaterTracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

  description: This is a documentation of water consumption app
tags:
  - name: Auth
    description: Auth operations.

  # юзера додати +
  - name: User
    description: Operations about users.

  - name: Water
    description: Operations about water.
servers:
  - url: http://localhost:3000
  - url: https://sevenwatertracker-back-1.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  #/auth/refresh:
  #  post:
  #   $ref: ../swagger/paths/auth/refresh/post.yaml
  /user:
    get:
      $ref: ../swagger/paths/user/get.yaml
    put:
      $ref: ../swagger/paths/user/put.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/avatar/patch.yaml
  /user/daily-norm:
    put:
      $ref: ../swagger/paths/user/daily-norm/put.yaml
  /user/email:
    post:
      $ref: ../swagger/paths/user/email/post.yaml

  /water:
    post:
      security:
        - bearerAuth: []
      # security: додати у всіх не auth
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month/get.yaml
  /water/today:
    get:
      $ref: ../swagger/paths/water/today/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
