openapi: 3.1.0
info:
  version: 1.0.0
  title: 7WaterTracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

  description: This is a documentation of water consumption app
tags:
  - name: Auth
    description: Auth operations.
  - name: User
    description: Operations about users.
  - name: Water
    description: Operations about water.
servers:
  - url: https://sevenwatertracker-back-1.onrender.com
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /user/info:
    get:
      $ref: ../swagger/paths/user/info/get.yaml
    put:
      $ref: ../swagger/paths/user/info/put.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/avatar/patch.yaml
  /user/daily-norm:
    put:
      $ref: ../swagger/paths/user/daily-norm/put.yaml
  /water/note:
    get:
      $ref: ../swagger/paths/water/note/get.yaml
    post:
      $ref: ../swagger/paths/water/note/post.yaml
  /water/note/{id}:
    patch:
      $ref: ../swagger/paths/water/note/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/note/{id}/delete.yaml
  /water/today:
    get:
      $ref: ../swagger/paths/water/today/get.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month/get.yaml


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
