openapi: 3.1.0
info:
  version: 1.0.0
<<<<<<< Updated upstream
=======
<<<<<<< HEAD
<<<<<<< HEAD
  title: 7WaterTracker
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of 7WaterTracker
tags:
  - name: Users
    description: Operations about users.
=======
=======
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
>>>>>>> Stashed changes
  title: 7WaterTracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
<<<<<<< Updated upstream
<<<<<<< HEAD
<<<<<<< HEAD
  description: This is a documentation of 7WaterTracker app
=======
  description: This is a documentation of contacts app
>>>>>>> da5454c3198e4589f1f50af6404371bff77ae8de
=======
  description: This is a documentation of contacts app
>>>>>>> da5454c3198e4589f1f50af6404371bff77ae8de
tags:
  - name: Users
    description: Operations about users.
=======
  description: This is a documentation of contacts app
tags:
<<<<<<< Updated upstream
=======
<<<<<<< HEAD
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
=======
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
>>>>>>> Stashed changes
>>>>>>> Stashed changes
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
<<<<<<< Updated upstream
  - url: https://sevenwatertracker-back-1.onrender.com
<<<<<<< HEAD
   
=======
<<<<<<< HEAD
<<<<<<< HEAD
  - url:
paths: $ref: ../swagger/paths/users/{id}/get.yaml
=======
  - url: https://sevenwatertracker-back-1.onrender.com
<<<<<<< Updated upstream
<<<<<<< HEAD
<<<<<<< HEAD
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh/post.yaml
  /users:
    post:
      $ref: ../swagger/paths/users/post.yaml
  /users/{id}:
    get:
      $ref: ../swagger/paths/users/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/users/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/users/{id}/delete.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{date}:
    patch:
      $ref: ../swagger/paths/water/{date}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{date}/delete.yaml
  /water/waterDay:
    get:
      $ref: ../swagger/paths/water/waterDay/get.yaml
  /water/waterMonth:
    get:
      $ref: ../swagger/paths/water/waterMonth/get.yaml
=======
>>>>>>> da5454c3198e4589f1f50af6404371bff77ae8de
=======
>>>>>>> da5454c3198e4589f1f50af6404371bff77ae8de
=======
   
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
=======
  - url: https://sevenwatertracker-back-1.onrender.com
   
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
>>>>>>> Stashed changes
=======
>>>>>>> 343e630a102cd6c5382a022875952dd28c7826bc
>>>>>>> Stashed changes
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
<<<<<<< Updated upstream
=======
<<<<<<< HEAD
<<<<<<< Updated upstream

      
=======
<<<<<<< HEAD
<<<<<<< HEAD
=======

      
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
=======

      
>>>>>>> 9e1efba9541c02d7378373a4c82dfb049adc911a
>>>>>>> Stashed changes
=======
>>>>>>> 343e630a102cd6c5382a022875952dd28c7826bc
>>>>>>> Stashed changes
