openapi: 3.1.0
info:
  version: 1.0.0
  title: 7WaterTracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

  description: This is a documentation of water consumption app
tags:
  - name: Auth
    description: Auth operations.
# юзера додати
  - name: Water
    description: Operations about water.
servers:
  - url: http://localhost:3000
  - url: https://sevenwatertracker-back-1.onrender.com
paths:
  /auth/registration:
    post:
      $ref: ../swagger/paths/auth/registration/post.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout/post.yaml
  # /auth/refresh: рефреш в нас немає, але може напишемо
  #   post:
  #     $ref: ../swagger/paths/auth/refresh/post.yaml
  /water:
    post:
      security:
        - bearerAuth: []
      # security: додати у всіх не auth
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/month:
    get:
      $ref: ../swagger/paths/water/month/get.yaml
  /water/today:
    get:
      $ref: ../swagger/paths/water/today/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
